git-file-changes-in-umerged: tries to find the default branch instead of alwats assuming master

diff --git a/salt/states/development/home/.local/bin/git-file-changes-in-umerged b/salt/states/development/home/.local/bin/git-file-changes-in-umerged
--- a/salt/states/development/home/.local/bin/git-file-changes-in-umerged
+++ b/salt/states/development/home/.local/bin/git-file-changes-in-umerged
@@ -5,18 +5,39 @@ trim_lines()
     awk '{$1=$1};1'
 }
 
+# TODO: change to a git script/alias so it can be reused
+git_assumed_default_branch()
+{
+    if git show-ref --verify --quiet refs/heads/main; then
+        echo 'main'
+    elif git show-ref --verify --quiet refs/heads/master; then
+        echo 'master'
+    elif git show-ref --verify --quiet refs/heads/develop; then
+        echo 'develop'
+    else
+        echo "$0: could not determine default branch for repo" 1>&2
+        return 1
+    fi
+}
+
 main()
 {
     declare ignore_branches="$1"
     declare path="$2"
 
     if [[ -z "$path" ]]; then
-        echo "Must provide path"
+        echo "usage: $0 <ignore-branches> <path>"
+        echo "   ie. $0 'staging|uat' package-lock.json"
         return 1
     fi
 
-    # TODO: should I change this to origin/master? also, what about repo's with a different main branch (probs introduce a command the guess the main branch, main || master || develop || etc., first that exists locally is assumed to be the trunk)
-    unmerged_branches="`git branch --no-merged master --remote | trim_lines | egrep -v "/($ignore_branches)$"`"
+    declare default_branch="$(git_assumed_default_branch)"
+    if [[ -z "$default_branch" ]]; then
+        return 1
+    fi
+
+    # TODO: should I change this to origin/{default_branch}?
+    unmerged_branches="`git branch --no-merged "$default_branch" --remote | trim_lines | egrep -v "/($ignore_branches)$"`"
 
     for branch in $unmerged_branches; do
         :
