setup devshell with shellcheck and shfmt, added pre-commit hooks to lint shell scripts

diff --git a/home/.local/bin/repo b/home/.local/bin/repo
--- a/home/.local/bin/repo
+++ b/home/.local/bin/repo
@@ -25,15 +25,18 @@ base_url=${base_url//git@bitbucket.org:/https:\/\/bitbucket\.org\/}
 base_url=${base_url//git@gitlab\.com:/https:\/\/gitlab\.com\/}
 
 # Validate that this folder is a git folder
-if ! git branch 2>/dev/null 1>&2 ; then
+if ! git branch 2>/dev/null 1>&2; then
     echo "Not a git repo!"
     exit 1
 fi
 
 # Find current directory relative to .git parent
 full_path=$(pwd)
-git_base_path=$(cd "./$(git rev-parse --show-cdup)" || exit 1; pwd)
-relative_path=${full_path#$git_base_path} # remove leading git_base_path from working directory
+git_base_path=$(
+    cd "./$(git rev-parse --show-cdup)" || exit 1
+    pwd
+)
+relative_path=${full_path#"$git_base_path"} # remove leading git_base_path from working directory
 
 # If filename argument is present, append it
 if [ "$1" ]; then
@@ -52,9 +55,9 @@ branch=${git_where#remotes\/origin\/}
 url="$base_url/$tree/$branch$relative_path"
 
 if type xdg-open >/dev/null 2>&1; then
-    xdg-open "$url" &> /dev/null || (echo "Using $(type xdg-open) to open URL failed." && exit 1);
+    xdg-open "$url" &>/dev/null || (echo "Using $(type xdg-open) to open URL failed." && exit 1)
 elif type open >/dev/null 2>&1; then
-    open "$url" &> /dev/null || (echo "Using $(type open) to open URL failed." && exit 1);
+    open "$url" &>/dev/null || (echo "Using $(type open) to open URL failed." && exit 1)
 else
     echo "could not find command to open: ${url}"
 fi
