tuber: download videos which require auth

diff --git a/home/.local/bin/tuber b/home/.local/bin/tuber
--- a/home/.local/bin/tuber
+++ b/home/.local/bin/tuber
@@ -2,6 +2,8 @@
 
 set -e
 
+trap 'exit 1' INT
+
 usage() {
     echo 'Manage downloaded youtube videos from a playlist'
     echo "${colour_bold}usage:${colour_reset} tuber <playlist-url> [--output-directory <directory>]"
@@ -101,6 +103,36 @@ array::contains() {
     return 1
 }
 
+fetch_video_details() {
+    declare id="$1"
+    if [[ -z "$id" ]]; then
+        echo 'fetch_video_details: missing required param <id>'
+        return 1
+    fi
+
+    declare -a video_details_cmd=(
+        "${cache_cmd[@]}" \
+        yt-dlp \
+            --preset-alias sleep \
+            --dump-single-json
+    )
+
+    # try to get details without with
+    if ! "${video_details_cmd[@]}" -- "$id" 2>/dev/null; then
+        # TODO: could be smarter about this...
+        # assume video requires auth if the first fetch fails
+        if [[ -v video_requires_auth ]]; then
+            video_requires_auth='true'
+        fi
+
+        # fallback to getting details with auth
+        "${video_details_cmd[@]}" \
+            --cookies-from-browser firefox \
+            -- \
+            "$id"
+    fi
+}
+
 declare colour_blue=''
 colour_blue="$(tput setaf 4)"
 declare colour_bold=''
@@ -140,11 +172,12 @@ fi
 declare playlist_video_ids
 readarray -t playlist_video_ids <<< "$(jq -r --compact-output '.entries[].id' <<< "$playlist_details")"
 
-# delete existing files which are no longer in the playlist
+# find existing files
 echo "${colour_blue}${colour_bold}[tuber:info] cleaning up existing files ${colour_reset}"
 declare -a existing_video_ids=()
 declare existing_files
 readarray -t existing_files <<<"$(find "$output_directory" -type f -iname '*\[*\].*')"
+
 for file in "${existing_files[@]}"; do
     # extract id
     declare id=''
@@ -159,13 +192,13 @@ for file in "${existing_files[@]}"; do
     elif [[ "$extension" == 'mp4' ]]; then
         existing_video_ids+=("$id")
     else
-        echo "unrecognized extension: ${extension}"
+        echo "unrecognized extension: ${extension} of file ${file} " >&2
         exit 1
     fi
 
     # delete if it's no longer in the playlist
     if ! array::contains "$id" "${playlist_video_ids[@]}"; then
-        echo "${colour_blue}${colour_bold}[tuber:info] rm ${file}"
+        echo "${colour_blue}${colour_bold}[tuber:info] rm ${file}${colour_reset}"
         "${dry_run_cmd[@]}" rm -rf "$file"
     fi
 done
@@ -173,21 +206,14 @@ done
 # Download each video
 for id in "${playlist_video_ids[@]}"; do
     if array::contains "$id" "${existing_video_ids[@]}"; then
-        echo "${colour_blue}${colour_bold}[tuber:info] skipping already downloaded ${id}"
-    else
-        echo "${colour_blue}${colour_bold}[tuber:info] downloading ${id}: ${channel} - ${title}${colour_reset}"
+        echo "${colour_blue}${colour_bold}[tuber:info] skipping already downloaded ${id}${colour_reset}"
+        continue
     fi
 
-    # TODO: as required: --cookies-from-browser firefox (maybe we can detect error reason instead of continuing on error)
+    # fetch video details
+    declare video_requires_auth='false'
     declare video_details=''
-    video_details="${
-        "${cache_cmd[@]}" \
-        yt-dlp \
-            --preset-alias sleep \
-            --dump-single-json \
-            "$id" \
-            || continue
-    }"
+    video_details="${ fetch_video_details "$id"; }"
 
     if [[ "$debug" == 'true' ]]; then
         echo "[tuber:debug] id: ${id} video_details: ${video_details}"
@@ -198,10 +224,17 @@ for id in "${playlist_video_ids[@]}"; do
     declare title=''
     title="$(jq -r --compact-output '.title' <<< "$video_details")"
 
+    echo "${colour_blue}${colour_bold}[tuber:info] downloading ${id}: ${channel} - ${title}${colour_reset}"
+
+    declare -a download_args=()
+    if [[ "$video_requires_auth" == 'true' ]]; then
+        download_args+=(--cookies-from-browser firefox)
+    fi
 
     # download
     "${dry_run_cmd[@]}" \
     yt-dlp \
+        "${download_args[@]}" \
         --preset-alias 'sleep' \
         --embed-chapters \
         --embed-metadata \
@@ -211,5 +244,6 @@ for id in "${playlist_video_ids[@]}"; do
         --paths "temp:${HOME}/.cache/tuber" \
         --paths "home:${output_directory}" \
         --output "%(uploader)s/%(uploader)s - %(upload_date>%Y-%m-%d)s: %(title)s [%(id)s].%(ext)s" \
+        -- \
         "$id"
 done
