?? shell function now uses bat by default, added clear_echo command, fix repo cli on linux, updated npmrc, auto format more files in sublime, added pentible sublime projects directory, misc other tweaks

diff --git a/salt/states/base/home/.local/bin/repo b/salt/states/base/home/.local/bin/repo
--- a/salt/states/base/home/.local/bin/repo
+++ b/salt/states/base/home/.local/bin/repo
@@ -51,4 +51,10 @@ branch=${git_where#remotes\/origin\/}
 [[ $base_url == *bitbucket* ]] && tree="src" || tree="tree"
 url="$base_url/$tree/$branch$relative_path"
 
-open "$url" &> /dev/null || (echo "Using $(type open) to open URL failed." && exit 1);
+if type xdg-open >/dev/null 2>&1; then
+    xdg-open "$url" &> /dev/null || (echo "Using $(type xdg-open) to open URL failed." && exit 1);
+elif type open >/dev/null 2>&1; then
+    open "$url" &> /dev/null || (echo "Using $(type open) to open URL failed." && exit 1);
+else
+    echo "could not find command to open: ${url}"
+fi
