ignoring bootstrap errors for now (for some reason it's returning exit code 1 without any visible errors...)

diff --git a/scripts/setup-salt b/scripts/setup-salt
--- a/scripts/setup-salt
+++ b/scripts/setup-salt
@@ -75,4 +75,5 @@ if [[ -n "$machine" ]]; then
 fi
 
 # apply bootstrap state (for installing package managers and such)
-salt-call --local state.apply bootstrap
+# TODO: this is returning exit code 1 without any visible errors...
+salt-call --local state.apply bootstrap || true
